//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationReceivers
    {
        public int Id { get; set; }
        public string ApplicationUserId { get; set; }
        public int NotificationId { get; set; }
    
        public virtual ApplicationUser ApplicationUser { get; set; }
        public virtual Notification Notification { get; set; }
    }
}
