//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public Notification()
        {
            this.NotificationReceivers = new HashSet<NotificationReceivers>();
        }
    
        public int Id { get; set; }
        public string Content { get; set; }
    
        public virtual ICollection<NotificationReceivers> NotificationReceivers { get; set; }
        public virtual NotificationSenders NotificationSender { get; set; }
    }
}
