//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskStudent
    {
        public TaskStudent()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Mark { get; set; }
        public string ApplicationUserId { get; set; }
        public int TaskId { get; set; }
    
        public virtual ApplicationUser Student { get; set; }
        public virtual Task Task { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
